import pandas as pd
import os
import subprocess
import re

# Paths
results_path = "REPLACE WITH YOUR PATH"
base_output_path = "REPLACE WITH YOUR PATH"

def clean_stata_string(text):
    """Strips quotes and LaTeX artifacts generated by Stata's esttab."""
    if not isinstance(text, str): return text
    # Remove literal quotes and Stata artifacts
    text = text.replace('"', '').replace('$', '').replace('=', '')
    text = text.replace(r'\prime', '').replace(r'\prime\prime', '')
    # Escape underscores for LaTeX using raw string logic
    text = text.replace('_', r'\_')
    return text.strip()

def get_spec_legend():
    """Returns the vertical footnote explaining the 7 specifications."""
    return r"""
    \vspace{0.2cm}
    \begin{flushleft}
    \footnotesize
    \textbf{Notes:} Standard errors are in parentheses. * p < 0.1, ** p < 0.05, *** p < 0.01. All models include internal quality and small entity controls. \\
    (1) OLS baseline \\
    (2) OLS + robust SE \\
    (3) Tech FE \\
    (4) Year FE \\
    (5) Tech + Year FE \\
    (6) Tech FE, SE clustered by Year \\
    (7) Year FE, SE clustered by Tech
    \end{flushleft}
    """

def compile_pdf(tex_content, output_dir, filename):
    template = r"""
    \documentclass{article}
    \usepackage[utf8]{inputenc}
    \usepackage{booktabs}
    \usepackage{geometry}
    \usepackage{caption}
    \geometry{letterpaper, margin=0.5in, landscape}
    \begin{document}
    \centering
    %s
    \end{document}
    """ % tex_content
    
    tex_path = os.path.join(output_dir, f"{filename}.tex")
    with open(tex_path, "w") as f:
        f.write(template)
    
    try:
        subprocess.run(
            ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", "-output-directory", output_dir, tex_path],
            check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
        )
        print(f"Successfully compiled {filename}.pdf")
    except subprocess.CalledProcessError:
        print(f"Error compiling {filename}. Manual check of .tex required.")

def process_results():
    if not os.path.exists(base_output_path): os.makedirs(base_output_path)
    
    category_fragments = {}

    for file in sorted(os.listdir(results_path)):
        if not file.endswith(".csv"): continue
        
        parts = file.replace("reg_", "").replace(".csv", "").split("_")
        measure_with_window = parts[0]
        level = parts[1]
        measure_type = re.sub(r'\d+', '', measure_with_window)
        category_key = f"{measure_type}_{level}"
        
        measure_folder = os.path.join(base_output_path, measure_type)
        if not os.path.exists(measure_folder): os.makedirs(measure_folder)

        df = pd.read_csv(os.path.join(results_path, file))
        df = df.map(clean_stata_string)
        
        df.columns = ["Variable"] + [f"({i})" for i in range(1, len(df.columns))]
        
        label_map = {
            r"log\\\_internal\\\_quality": "Internal Quality (log)",
            r"is\\\_small": "Small Entity",
            "Obs": "Observations",
            "R2": "R-Squared",
            "ren1": "Renewal Decision (Year 4)",
            "ren2": "Renewal Decision (Year 8)",
            "ren3": "Renewal Decision (Year 12)"
        }
        for old, new in label_map.items():
            df["Variable"] = df["Variable"].str.replace(old, new, regex=True)

        comp_pattern = f"log\\_{measure_with_window.lower()}\\_{level.lower()}".replace("_", r"\\\_")
        df["Variable"] = df["Variable"].str.replace(comp_pattern, f"Competition: {measure_type}", regex=True)

        tex_table = df.style.hide(axis="index").to_latex(
            hrules=True, 
            caption=f"Robustness: {measure_type} ({level}) - {measure_with_window}", 
            column_format="l" + "c"*(len(df.columns)-1)
        )
        
        full_content = tex_table + get_spec_legend()
        compile_pdf(full_content, measure_folder, f"Table_{measure_with_window}_{level}")
        
        if category_key not in category_fragments: category_fragments[category_key] = []
        category_fragments[category_key].append(full_content)

    for cat, fragments in category_fragments.items():
        combined_content = r"\newpage ".join(fragments)
        compile_pdf(combined_content, base_output_path, f"COMBINED_{cat}")
        print(f"Generated Combined PDF for {cat}")

if __name__ == "__main__":
    process_results()
